# Start with a base image containing Java runtime
FROM openjdk:8
# Add the application's jar to the container
ADD target/assecor-0.0.1-SNAPSHOT.jar assecor.jar
# Make port 8085 available to outside this container
EXPOSE 8085
# Run the jar file on command line
ENTRYPOINT ["java","-jar","assecor.jar"]